title: Arya Singh's Website
subtitle: Computer Science Student
description: >-
  A passionate developer exploring the realms of computer science and software engineering.

url: "" # Add your site's URL if applicable
baseurl: "" # Add the subpath of your site, e.g., /portfolio

# Navigation
urls:
  - text: Home
    url: /
  - text: About
    url: /about
  - text: Blog
    url: /blog
  - text: Projects
    url: /projects
  - text: Contact
    url: /contact

# Author Details
author_logo: profile.png
author: Arya Singh
author_bio: A passionate developer exploring the realms of computer science and software engineering.
author_email: ads26@sfu.ca
author_location: Burnaby, B.C.
author_website_url: "https://github.com/AryaDSingh"

# Technical Skills
technical_skills:
  - Java
  - C/C++
  - Python
  - Haskell
  - SQL
  - HTML
  - JavaScript
  - CSS
  - Rasterization Pipeline
  - Elementor
  - WordPress
  - OpenGL
  - Figma
  - Unreal Engine
  - Linux / Linux Shell
  - Balsamiq
  - Git (GitHub and GitLab)
  - Data Structures
  - Algorithm design/analysis
  - Object Oriented Programming
  - Eclipse (IDE)
  - Visual Studio Code (IDE)
  - Android Studio (IDE)
  - Iterative Project Development
  - Android Programming
  - Unit Testing
  - Acceptance Testing
  - Heuristic Evaluation
  - Requirements Gathering
  - Microsoft Office (Word, Excel, Outlook, PowerPoint)

# Technical Projects
technical_projects:
  - project_thumbnail: night_sky.png
    project_title: Night Sky
    project_description: >
      JavaScript code that aims to create an animated space image using HTML5 and the 2D rendering context.
      Most aspects of the project are randomly generated, resulting in a different scene during runtime.
      Uses Global Alpha to control the opacity of various elements, allowing for fading and transparency effects.
      Uses an animation loop to continuously update the canvas to create dynamic effects.

  - project_thumbnail: cow_render.png
    project_title: Cow Render
    project_description: >
      A render of a cow with two light sources in HTML and CSS, using Rasterization in WebGL.
      User interaction allows scaling, translation, and rotation of the image.
      Uses an animation loop to continuously update positions of the cow and lighting.
      Uses Phong reflection and shading to make the cow appear realistic, 3D, and smooth.

  - project_thumbnail: mountain_language.png
    project_title: Mountain Language
    project_description: >
      Created a program for the 2023 Mountain Madness Hackathon with a theme of "Lost in Translation" and "Mountainous."
      Allows users to send messages with a mountain-themed twist.
      Uses the Sockets API in Python to send messages across a network.
      The message is ciphered using a dictionary full of mountainous language and sent to another user who can translate it.

  - project_thumbnail: sudoku_game.png
    project_title: Sudoku Language Game
    project_description: >
      Designed a Sudoku game that allows the user to practice a language of their choice using Sudoku.
      Implemented features as per the customer's (instructors) needs.
      Created and ran unit tests (JUnit) and UI tests to quickly and efficiently test the application against new features.

# Social Links
twitter_username: "" # Add your Twitter username
github_username: "AryaDSingh"
linkedin_username: "arya-singh-296b081bb"

# ...

# Education
author_education_details:
  - college_logo: sfu.png
    college_name: Simon Fraser University
    college_url: "https://www.sfu.ca"
    college_degree: B.S Computing Science
    description: Expected graduation: 2024

# Work Experience
author_work_experiences:
  - company_name: CCCIA
    company_logo: cccia_logo.png
    company_url: "https://ccciasurrey.ca"
    designation: Website Developer
    description: >
      Design and develop user-friendly websites that reflect our organization's mission.
      Collaborate with the team to understand project requirements and create design concepts.
      Customize website templates or create custom designs using web design technologies.
      Update and maintain existing websites, adding content and making improvements.
      Test websites for functionality and troubleshoot any issues.

  - company_name: Hawkeye Drone Academy
    company_logo: hawkeye_logo.png
    company_url: "https://www.hawkeyedroneacademy.ca"
    designation: Instructor
    description: >
      Developed an introductory course on Python with a focus on unplugged learning directed towards elementary and high school kids.
      Learned and used Sphero to create fun and engaging interactive lessons to drive stronger retention of topics.
      Designed projects, activities, and games that allow for very hands-on programming.

# ...

# Hobbies + Interests
hobbies_and_interests:
  - Training at the gym
  - Video Games
  - TV Shows
  - Music
  - Anime
  - Volleyball
  - Pickleball
