title: Arya Singh
subtitle: Computer Science Student
description: >- # this means to ignore newlines until "baseurl:"
  A passionate developer exploring the realms of computer science and software engineering.

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# Navigation
urls:
    - text: About
      url: /about

# Edit Author details (For multi authors check _data/authors.yml)

author_logo: bitmoji.jpg
author: Arya Singh
author_bio: Hi, my name is Arya Singh. I am a 4th year computer science student at SFU. I am currently looking for a co op.
author_email: "ads26@sfu.ca"
author_location: Canada
author_website_url: "https://aryadsingh.github.io"
typewrite-text: Welcome to my Website
hero_cover_img: sample_cover.jpg # replace this for changing homepage cover (eg. try cover.jpeg). Image should be in /assets/img

# Experiences
author_work_experiences:
            - company_name: CCCIA
              company_logo: CCCIA.jfif
              company_url: http://www.cccia.ca/
              designation: Web Developer
              description: Customize website templates or create custom designs using web design technologies. Update and maintain existing websites, adding content and making improvements. Test webpages for functionality and troubleshoot any issues.
              visibility: true
            - company_name: Hawkeye Drone Academy
              company_logo: hawkeye.jfif
              company_url: "https://www.hawkeyesdrone.ca/"
              designation: Intructor
              description: Taught children how to code! Developed an introductory course on Python with a focus on unplugged learning directed towards elementary and high school kids. Learned and used Sphero to create fun and engaging interactive lessons to drive stronger retention of topics. Designed projects, activities, and games that allow for very hands-on programming.
              visibility: true

# Education
author_education_details:
              - college_logo: sfulogo.jpeg
                college_name: SFU
                college_url: http://www.sfu.ca/
                college_degree: Computer Science
                description: Bachelor of Applied Science
                visibility: true

# Technical Projects
author_project_details:

  - project_thumbnail: dither.JPG
    project_title: Tiff Image Processing
    project_description: >
      Developed a TIFF image processing application in C++ using the Qt
      framework for a graphical user interface.
      Implemented various image processing modes, including brightness
      reduction, ordered dithering, and auto-level adjustment.
      Utilized a 2x2 dither matrix for ordered dithering to convert
      grayscale images into binary images.
      Integrated keyboard event handling to allow users to cycle through
      different processing modes.
      Provided a user-friendly interface for opening TIFF files, viewing
      original images, and applying diverse processing techniques.
    project_url: "https://github.com/AryaDSingh/Tiff-Image-Processing-"
    visibility: true

  - project_thumbnail: audio1wav.JPG
    project_title: Waveform Plotter
    project_description: >
      Developed a sophisticated waveform plotter application in C++ using
      the Qt framework, offering a dynamic graphical representation of
      audio waveforms.
      Implemented various signal processing functionalities, including
      downsampling for efficient visualization of large audio files, ensuring
      optimal performance and user experience.
      Used compression techniques such as Huffman and Shannon
      Fanocoding to showcase average code word length and entropy.
      Integrated file handling mechanisms, allowing users to open and
      analyze .wav files seamlessly, with detailed information about the
      audio file displayed for user understanding.
   
    project_url: ""
    visibility: true

  - project_thumbnail: myScene.JPG
    project_title: Night Sky
    project_description: >
      JavaScript code that aims to create an animated space image using HTML5 and the 2D rendering context.
      Most aspects of the project are randomly generated, resulting in a different scene during runtime.
      Uses Global Alpha to control the opacity of various elements, allowing for fading and transparency effects.
      Uses an animation loop to continuously update the canvas to create dynamic effects.
    project_url: "https://github.com/AryaDSingh/NightSky"
    visibility: true

  - project_thumbnail: cowpic.jpg
    project_title: Cow Shading Render
    project_description: >
      A render of a cow with two light sources in HTML and CSS, using Rasterization in WebGL.
      User interaction allows scaling, translation, and rotation of the image.
      Uses an animation loop to continuously update positions of the cow and lighting.
      Uses Phong reflection and shading to make the cow appear realistic, 3D, and smooth.
    project_url: "https://github.com/AryaDSingh/CowShading"
    visibility: true

  - project_thumbnail: mountain.png
    project_title: Mountain Language
    project_description: >
      Created a program for the 2023 Mountain Madness Hackathon with a theme of "Lost in Translation" and "Mountainous."
      Allows users to send messages with a mountain-themed twist.
      Uses the Sockets API in Python to send messages across a network.
      The message is ciphered using a dictionary full of mountainous language and sent to another user who can translate it.
    project_url: "https://github.com/AryaDSingh/2023-Mountain-Madness-Hackathon-Project-"
    visibility: true

  - project_thumbnail: sudoku.png
    project_title: Sudoku Language Game
    project_description: >
      Designed a Sudoku game that allows the user to practice a language of their choice using Sudoku.
      Implemented features as per the customer's (instructors) needs.
      Created and ran unit tests (JUnit) and UI tests to quickly and efficiently test the application against new features.
    project_url: "https://github.com/AryaDSingh/Java-Sudoku-Group-Project-CMPT-276"
    visibility: true



            

# social links
github_username: AryaDSingh
linkedin_username: arya-singh-296b081bb



# wakatime username (coding activity)
wakatime_username: Arya Singh

# contact form - (choose formspress or getform)
# getform_endpoint: 83b703c3-9e47-4df4-ac55-e24d7eb02abc
formspree_email: ads26@sfu.ca


# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: false
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug
  -
    scope:
      path: 'assets/**'
    values:
      sitemap: false

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-admin

# Jekyll Admin Config
jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  homepage: "/about"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

### Switching Deployment Strategy (in DEPLOY_STRATEGY) file change the key accordingly:
# none - For no default
# gh-pages - For Github Pages
# firebase - For Firebase Hosting

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - assets/bower_components/isotope-layout/README.md
  - assets/bower_components/icono/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-svg-core/README.md
  - assets/bower_components/ghosthunter/README.md
  - assets/bower_components/nanobar/README.md
  - assets/bower_components/lightgallery/demo/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-brands-svg-icons/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-solid-svg-icons/README.md
  - assets/bower_components/jquery-mousewheel/README.md
  - assets/bower_components/get-size/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome/README.md
  - assets/bower_components/jquery-mousewheel/ChangeLog/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-regular/README.md
  - assets/bower_components/desandro-matches-selector/README.md
  - assets/bower_components/ev-emitter/README.md
  - assets/bower_components/font-awesome/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-solid/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-webfonts/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-brands/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-common-types/README.md
  - assets/bower_components/ghosthunter/example/Index.html
  - assets/bower_components/lightgallery/test/lightgallery.html
  - assets/bower_components/masonry-layout/README.md
  - assets/bower_components/imagesloaded/README.md


destination: ./build
